#!/bin/bash
# Run Django, also on the external interfaces for iPad testing.
# 'bdr' is a mnemonic for 'bin django runserver'.
# Note that I'm mostly running django inside dockers nowadays :-)

docker-compose run --service-ports web bin/django runserver 0.0.0.0:5000
