#!/bin/bash
# Remove all the intermediary/on-the-fly docker images that aren't used
# anymore. Every time you run a docker/docker-compose command a new image is
# created and stored. Probably not big, but you don't need it.
#
# You can start docker-compose with the ``--rm`` option to clean up after
# itself. This ``drm`` command cleans up the cases where you didn't use
# ``--rm``.

echo "If there is nothing to remove, some commands will raise an error. That's OK."
docker rm $(docker ps -aq)
docker rm -v $(docker ps --filter status=exited -q 2>/dev/null)
docker rmi $(docker images --quiet --filter "dangling=true")
