#!/bin/bash
# Remove all the intermediary/on-the-fly docker images that aren't used
# anymore. Every time you run a docker/docker-compose command a new image is
# created and stored. Probably not big, but you don't need it.
#
# You can start docker-compose with the ``--rm`` option to clean up after
# itself. This ``drm`` command cleans up the cases where you didn't use
# ``--rm``.
#
# The second command removes intermediary dangling images.

docker rm $(docker ps -aq)
echo "If there is nothing to remove, the next command will raise an error. That's OK."
docker rmi $(docker images --quiet --filter "dangling=true")
