#!/bin/bash
# Just print out the disk usage *totals* for every directory in the current
# directory.
#
# -h = Human readable
# -c = Show the grand total, too.
# -s = Show only the total size of the arguments: don't display the recursive
#      information.

du -hcs *
