#!/bin/bash
# Just print out the disk usage *totals* for every directory in the current
# directory.
#
# -m  = In megabytes (for easy "| sort -n")
# -d1 = Current directory + one level below

du -m -d1
