#!/bin/bash
# Undelete a file from git which has been git-rm'ed and git-commit'ed somewhere in the
# past. See https://stackoverflow.com/a/1113140/27401
#
# Pass a filename (some_dir/some_file.txt) you want restored.

git checkout $(git rev-list -n 1 HEAD -- "$1")^ -- "$1"
