#!/bin/bash
# Run 'hadolint', a Dockerfile syntax checker, via docker, as suggested by
# https://github.com/hadolint/hadolint. hadolint is used by emacs' flycheck,
# see http://www.flycheck.org/en/latest/languages.html#dockerfile

docker run --rm -i hadolint/hadolint
