#!/bin/bash
# Use pandoc to convert a .md file to docx.
#
# I originally used the `markdown` format, but I've switched to `gfm`, github
# flavoured markdown, because that auto-renders URLS.
set -e
set -u
pandoc -f gfm -t html5 $1 -o ${1%.md}.html
