#!/bin/bash
# Run code beautification from emacs' projectile
#
# I often want to run `black` or `ruff format` and so on the code for
# basic code beautification. This script is coupled to `C-c b` in
# emacs, it is intended to work inside a projectile project.
#
# - If the environment variable `PROJECTILE_BEAUTIFUL` is set, run that
#   command. The direnv program can help you set it automatically.
#
# - Normally `pre-commit run --all` is run
#

set -e
if [ -n "$PROJECTILE_BEAUTIFUL" ]; then
    eval $PROJECTILE_BEAUTIFUL
    exit
fi

exec pre-commit run --all
