#!/bin/bash
# Run some make/make/create job from emacs' projectile
#
# I often want to run `make html` or an arduino compilation and so on the code. This
# script is coupled to `C-c c` in emacs, it is intended to work inside a projectile
# project.
#
# - If the environment variable `PROJECTILE_MAKE` is set, run that
#   command. The direnv program can help you set it automatically.
#
# - If a makefile is present, `make` is run.
#

set -e
if [ -n "$PROJECTILE_MAKE" ]; then
    eval $PROJECTILE_MAKE
    exit
fi

if [ -f Makefile ]; then
    exec make
fi

echo "No Makefile found, set PROJECTILE_MAKE to some command"
exit 1
