#!/bin/bash
# Run tests from emacs' projectile
#
# Emacs' projectile project tool can run tests with `C-c p P`. I have
# that coupled to `C-c t`. In one project, you need to run
# `bin/pytest`, in another `make test`, in another
# `venv/bin/pytest`... This script attempts a couple of them. Note
# that projectile runs it in the project's root directory: handy.
#
# - If the environment variable `PROJECTILE_TEST` is set, run that
#   command. The direnv program can help you set it automatically.
#
# - .venv/bin/pytest (and the venv/bin and bin variants) is searched
#   for and run if found.

set -e
if [ -n "$PROJECTILE_TEST" ]; then
    eval $PROJECTILE_TEST
    exit
fi

for program in .venv/bin/pytest bin/pytest venv/bin/pytest
do
    if [ -f $program ]; then
        exec $program
    fi
done

echo "No test program found"
exit 1
