#!/bin/bash
# Run code checks from emacs' projectile
#
# I often want to run `pyflakes` or `ruff check` and so on the code
# for basic structure and syntax checking. This script is coupled to
#`C-c c` in emacs, it is intended to work inside a projectile project.
#
# - If the environment variable `PROJECTILE_CHECK` is set, run that
#   command. The direnv program can help you set it automatically.
#
# - If a makefile is present, `make check` is run.
#
# - `ruff` is run with check+fix as a fallback.
#

set -e
if [ -n "$PROJECTILE_CHECK" ]; then
    eval $PROJECTILE_CHECK
    exit
fi

if [ -f Makefile ]; then
    exec make check
fi

exec ruff check . --fix
