#!/bin/bash
# Run some compile/create job from emacs' projectile
#
# I often want to run `make html` or an arduino compilation and so on the code. This
# script is coupled to `C-c c` in emacs, it is intended to work inside a projectile
# project.
#
# - If the environment variable `PROJECTILE_COMPILE` is set, run that
#   command. The direnv program can help you set it automatically.
#
# - If a makefile is present, `make` is run.
#
# - `ruff` is run with check+fix as a fallback.
#

set -e
if [ -n "$PROJECTILE_CHECK" ]; then
    eval $PROJECTILE_CHECK
    exit
fi

if [ -f Makefile ]; then
    exec make
fi

echo "No Makefile found, set PROJECTILE_CHECK to some command"
exit 1
