#!/bin/bash
# Make a backup with restic (https://restic.readthedocs.io)
#
# `.restic-env-vars` contains environment variables like the S3 credentials and the
# repository location. `.restic-files` has the list of directories that need to be
# backed up.
set -e
source ~/.restic-env-vars
cd ~
/opt/homebrew/bin/restic backup --files-from ~/.restic-files

/opt/homebrew/bin/restic forget --keep-daily 7 --keep-monthly 12 --group-by '' --prune
