#!/bin/bash
# Grep for a term in the current directory, but with some twists:
#
# - Multiple terms are taken to be one big space-separated term.
#
# - ``.svn`` and ``.hg`` directories are ignored.
#
# - Same with ``egg-info`` and ``*.pyc`` files.
#
# - The search term is highlighted in the output.

SEARCHFOR=`echo "$*" | sed "s/ \/dev\/null//g"`
grep -rin "$SEARCHFOR" * | grep -v \\.svn | grep -v \\.hg | grep -v egg-info | grep -v \\.pyc: | grep -v \\.po: | grep -v bundle\\.js | grep -i --color=auto "$SEARCHFOR"
