#!/bin/bash
# Shows svn log, but with some better defaults:
#
# - It uses verbose mode (``-v``); this way it actually shows the files that
#   have been changed. This is often clearer than the log message itself.
#
# - It pipes it through "less" instead of blubbering your terminal full with
#   several pages' worth of logs.

svn -v log | less
